### ISSUE TITLE
好像出错了~

### ISSUE THREAD

**Issue by ycjcl868** [wssgcg1213/ling-cet-decoder#3]
![image](https://cloud.githubusercontent.com/assets/13595509/17770400/e80f70a8-656f-11e6-966e-f7d3c7a29d64.png)

查询前一天，99宿舍和学信网的接口，会不会变动？

**Comment by LDouble** [comment]
应该是改算法了吧～

**Comment by ycjcl868** [comment]
http://www.chsi.com.cn/cet/，学信网会不会改了接口？

**Comment by ycjcl868** [comment]
的确是改算法了，地址没变
![image](https://cloud.githubusercontent.com/assets/13595509/17794038/a4a449f0-65de-11e6-8249-0dce36f21e90.png)
